import { SalesOrder } from "./SalesOrder";


export interface Customer {
    CustomerId: number,
    RegDate: Date,
    CRN: string,
    Status: string,
    Name: string,
    ShortName: string,
    Email: string,
    Nature: string,
    ContactName: string,
    Cnic: string,
    ContactNumber: string,
    IsChargeBardana: boolean,
    IsShowReceivables: boolean,
    IsBedDebt: boolean,
    IsShowDn: boolean,
    IsSecurityDeposit: boolean,
    IsHeadQuater: boolean,
    IsBranch: boolean,
    CreditDays: number,
    CreditLimit: number,
    AgreedInvestment: number,
    Address: string,
    City: string,
    Country: string,
    LandlineNumber: string,
    MobilerNumber: string,
    FaxNumber: string,
    GroupName: string,
    StNumber: number,
    Ntn: string,
    SalesPersonId: number,
    CustomerTypeId: number,
    ModeOfPaymentId: number,
    SalesOrders: SalesOrder[]

}