export interface CustomerBank {
    customerBankId: number,
    name: string,
    bankCode: string,
    bankTitle: string,
    accountNumber: string,
    routingCode: string,
    swiftCode: string,
    remitCode: string,
    remitkey: string,
    uniqueId: string,
    remitTyoe: string,
    branchCode: string,
    branch: string,
    branchContactNumber: string,
    branchAddress: string,
    glCode: string,
    active: boolean,
    customerTypeId: number
}