export interface SalesPerson {
    salesPersonId: number,
    firstName: string,
    middleName: string,
    lastName: string,
    company: string,
    fullName: string,
    dOB: Date,
    placeOfBirth: string,
    occupation: string,
    nIC: string,
    gender: string,
    phoneNumber: string,
    remarks: string,
    residenceAddress: string,
    officeAddress: string,
    officeTel: string,
    foreignAddress: string,
    country: string,
    city: string,
    state: string,
    postalCode: string,
    distributorId: number
}