export interface Supplier {
    supplierId: number,
    code: string,
    status: string,
    name: string,
    address: string,
    city: string,
    country: string,
    landlineNumber: string,
    mobilerNumber: string,
    faxNumber: string,
    email: string,
    nature: string,
    contactName: string,
    contactNumber: string,
    glAccount: string,
}