export interface Supplier {
    SupplierId: number,
    Code: string,
    Status: string,
    Name: string,
    Address: string,
    City: string,
    Country: string,
    LandlineNumber: string,
    MobilerNumber: string,
    FaxNumber: string,
    Email: string,
    Nature: string,
    ContactName: string,
    ContactNumber: string,
    GlAccount: string,
}